// Interests for onboarding (choose up to 5) - matches design
export const ONBOARDING_INTERESTS = [
	"Hiking",
	"Photography",
	"Yoga",
	"Cooking",
	"Reading",
	"Live Music",
	"Art",
	"Camping",
	"Climbing",
	"Running",
	"Cultural Tours",
	"Solo Travel",
	"Backpacking",
	"Foodie Tours",
	"Scuba Diving",
	"Surfing",
	"Digital Nomad",
	"Volunteering",
	"Road Trips",
	"History Buff",
	"Nightlife",
	"Festivals",
	"Wildlife",
	"Sustainability",
	"Adventure Sports",
	"Beach Relaxation",
	"Mountain Biking",
	"Skiing",
	"Snowboarding",
	"Kayaking",
	"Rock Climbing",
	"Bungee Jumping",
	"Skydiving",
	"Hot Air Ballooning",
	"Wine Tasting",
	"Coffee Culture",
	"Street Food",
	"Local Markets",
	"Museums",
	"Architecture",
	"Street Art",
	"Music Festivals",
	"Dance",
	"Theater",
	"Meditation",
	"Wellness Retreats",
	"Spa Treatments",
	"Fitness",
	"CrossFit",
	"Cycling",
	"Marathon Running",
	"Triathlon",
	"Swimming",
	"Water Sports",
	"Sailing",
	"Fishing",
	"Bird Watching",
	"Star Gazing",
	"Camping Under Stars",
	"Glamping",
	"Hostels",
	"Luxury Travel",
	"Budget Travel",
	"Group Travel",
	"Family Travel",
	"Romantic Getaways",
	"Language Learning",
	"Teaching",
	"Cultural Exchange",
	"Local Traditions",
	"Self Discovery",
	"Technology",
	"Blogging",
	"Books & Literature",
	"Writing",
];

export const GENDER_OPTIONS = [
	{ value: "male", label: "Male" },
	{ value: "female", label: "Female" },
	{ value: "non-binary", label: "Non-binary" },
	{ value: "prefer-not-to-say", label: "Prefer not to say" },
];

// Common countries for dropdown (subset - can be expanded)
export const COUNTRIES = [
	"Israel",
	"United States",
	"United Kingdom",
	"Germany",
	"France",
	"Spain",
	"Italy",
	"Portugal",
	"Netherlands",
	"Canada",
	"Australia",
	"Japan",
	"Brazil",
	"Argentina",
	"Mexico",
	"India",
	"Thailand",
	"Indonesia",
	"South Korea",
	"Sweden",
	"Norway",
	"Denmark",
	"Poland",
	"Greece",
	"Turkey",
	"South Africa",
	"Egypt",
	"Morocco",
	"New Zealand",
	"Singapore",
	"Malaysia",
	"Vietnam",
	"Philippines",
	"Colombia",
	"Chile",
	"Peru",
	"Ecuador",
	"Costa Rica",
	"Ireland",
	"Switzerland",
	"Austria",
	"Belgium",
	"Czech Republic",
	"Hungary",
	"Romania",
	"Croatia",
	"Russia",
	"China",
	"Hong Kong",
	"Taiwan",
	"United Arab Emirates",
	"Saudi Arabia",
	"Other",
].sort();
